### ISSUE TITLE
AUTH_KEY_UNREGISTERED

### ISSUE THREAD

**Issue by jonathan3698** [sochix/TLSharp#631] opened 2017-11-10 03:59 UTC
https://github.com/sochix/TLSharp/issues/498

Seriously, I got the same thing. Same code from OP, except it doesn't work. Same diagnostics aswell (IsUserAuthorized = true, etc). I have been searching for hours. I go on Gitter, no answer from anyone since like september. Also, there's no documentation about this, and what are the cause of the error. Wtf? I mean to provide a library you must atleast provide that...

Seriously, I would pay for that kind of tool if atleast it was documented properly, really frustrating... I understand no one is getting paid here, and I am free to go take other tools, but I'm just stating my opinion because your library is awesome except this thing that is really important which does not take that much time to do. You guys probably spent more hours answering to people like me complaining than you would have if you had done a good documentation...

And yes, I have read the telegram API documentation and your documentation before saying this...

**Comment by jonathan3698** [comment] 2017-11-10 04:01
I want to mention that I used MakeAuthAsync multiple times, and after I integrated the code to load a session, but it returns a AUTH_KEY_UNREGISTERED message always. Here's my message on Gitter:

![image](https://user-images.githubusercontent.com/13685010/32642371-f45c7a98-c5a1-11e7-85b6-36e65b6a7b51.png)

**Comment by knocte** [comment] 2017-11-10 04:02
If this is a bug, then it's not a poor job at documentation. To fix bugs we need manpower. If you can dedicate your time to fix the bug, we welcome your efforts. By the way, this is a duplicate of #624, closing in favour of that one.

**Closed by knocte** 2017-11-10 04:02 UTC

**Comment by VDVuser** [comment] 2019-11-09 09:24
Hi! This works for me!
string fullPathToDat = Directory.GetCurrentDirectory() + "\session";
var store = new FileSessionStore();
client = new TelegramClient(apiId, apiHash, store, fullPathToDat);
await client.ConnectAsync(false);
