### ISSUE TITLE
Streaming new messages from a channel 

### ISSUE THREAD

**Issue by amirvenus** [sochix/TLSharp#692] opened 2018-01-27 10:45 UTC
Hi,
Is there anyway I can listen to a channel and have an event raised AS SOON AS a new message is posted on that channel without having to constantly send requests to compare the differences?

If sending requests on an interval in order to get the difference is the only way, what would be the interval in terms of milliseconds so that I can comply with the flood prevention policy?

Thanks

**Comment by messire** [comment] 2018-01-28 18:57
about 1000 ~1200 for me
U can experiment

**Comment by hosseinGanjyar** [comment] 2018-02-11 08:07
I solved this issue. please send your question in my group:
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog

**Comment by knocte** [comment] 2018-03-11 12:12
This seems to be a duplicate of this other bug report: https://github.com/sochix/TLSharp/issues/661 . Feel free to re-open if you think I'm mistaken. Thanks

**Closed by knocte** 2018-03-11 12:12 UTC

**Comment by hosseinGanjyar** [comment] 2019-02-08 15:36
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ
