### ISSUE TITLE
I cant register phone

### ISSUE THREAD

**Issue by WestSide072** [sochix/TLSharp#488] opened 2017-05-24 10:49 UTC
I try register phone
```
        async void RegAsync()
        {
            var client = new TelegramClient(173518, "d128620cc7c0c64c98a88693e20c45a3");

            await client.ConnectAsync(); // System.InvalidOperationException: "Can't decode packet"

            var phone = "...";

            var hash = await client.SendCodeRequestAsync(phone);
            var code = "<code_from_telegram>";
            await client.SignUpAsync(phone, hash, code, "first", "second");

        }
```

then i try 
```
        async void AuthAsync()
        {
            var client = new TelegramClient(173518, "d128620cc7c0c64c98a88693e20c45a3",
            null,
            "session",
            (ip, port) =>
            {
                var tcp = new TcpClient();
                tcp.Connect("149.154.167.50", 443);
                return tcp;
            });
            await client.ConnectAsync();

            var phone = "...";

            var hash = await client.SendCodeRequestAsync(phone);
            var code = "<code_from_telegram>";
            await client.SignUpAsync(phone, hash, code, "first", "second");

        }
```
its ok! I get sms code and input in 'code'.
But i try check phone and i have
```
         public async void CheckPhone()
        {
            var client = new TelegramClient(173518, "d128620cc7c0c64c98a88693e20c45a3",
null,
"session",
(ip, port) =>
{
    var tcp = new TcpClient();
    tcp.Connect("149.154.167.50", 443);
    return tcp;
});
            await client.ConnectAsync();
            var zz = await client.IsPhoneRegisteredAsync("..."); //System.InvalidOperationException: "PHONE_NUMBER_BANNED"
        }
```

Why telegram banned my phone? I tried many IPs for connects.. 
149.154.167.40 //System.InvalidOperationException: "Can't decode packet"
149.154.167.50//System.InvalidOperationException: "PHONE_NUMBER_BANNED"
149.154.167.51//System.InvalidOperationException: "PHONE_NUMBER_BANNED"

**Comment by rezamoradi0** [comment] 2017-05-31 13:47
TcpClient couldnot find
var tcp = new TcpClient();


Error	2	The type or namespace name 'TcpClient' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\reza\documents\visual studio 2012\Projects\TeleSharpTest\TeleSharpTest\Form1.cs	68	19	TeleSharpTest

**Comment by Axe-Usa** [comment] 2017-06-06 23:52
in my case happen the same i cant do any extension for tlsharp ;:(

**Comment by knocte** [comment] 2018-03-12 05:06
Duplicate of https://github.com/sochix/TLSharp/issues/561

**Closed by knocte** 2018-03-12 05:06 UTC
