### ISSUE TITLE
join to a channel 

### ISSUE THREAD

**Issue by hamedsadeghi190** [sochix/TLSharp#512] opened 2017-07-03 06:05 UTC
hi dear friends 
i need help for  join to a channel using  tlsharp.
please help me

**Comment by hosseinGanjyar** [comment] 2017-07-09 11:20
Do you solved your problem?

**Comment by hamedsadeghi190** [comment] 2017-07-10 05:30
var Channellist = (await Client.SendRequestAsync<TeleSharp.TL.Contacts.TLResolvedPeer>(
                                           new TeleSharp.TL.Contacts.TLRequestResolveUsername
                                           {
                                               username = "ChannelID"
                                           }).ConfigureAwait(true)).chats.lists;

                        if (Channellist.Count > 0)
                        {
                            var ChannelInfo = Channellist[0] as TeleSharp.TL.TLChannel;
                            var RequestJoin = new TeleSharp.TL.Channels.TLRequestJoinChannel()
                            {
                                channel = new TLInputChannel
                                {
                                    channel_id = ChannelInfo.id,
                                    access_hash = (long)ChannelInfo.access_hash
                                }
                            };
                            try
                            {
                                var JoinResponse = await Client.SendRequestAsync<Boolean>(RequestJoin);
                            }
                            catch (Exception ex)
                            {

                            }
                        }

**Comment by leila-net** [comment] 2017-07-12 09:24
hi dears,
I get Object reference not set to an instance of an object when using above code in first line in Client.SendRequestAsync<TeleSharp.TL.Contacts.TLResolvedPeer> ...

`
Line 480:
Line 481:
Line 482:            var Channellist = (await client.SendRequestAsync<TeleSharp.TL.Contacts.TLResolvedPeer>(
Line 483:            new TeleSharp.TL.Contacts.TLRequestResolveUsername
Line 484:            {`

**Comment by hamedsadeghi190** [comment] 2017-07-12 09:28
hi 
please check "Client" is  authenticated.

**Comment by leila-net** [comment] 2017-07-13 05:12
thanks for your quick response @hamedsadeghi190 ,
I forgot to connect to client first!!!

and one more question :)
could we get channel history like messages without join?
I used to get messages with GetHistoryAsync, but for channels that I am not joined , this method dose not have TLChannelMessages property so I could not get any messages.

**Comment by hosseinGanjyar** [comment] 2017-07-15 15:32
```

var client = new TelegramClient(apiId, apiHash);
await client.ConnectAsync();

var found = await client.SearchUserAsync(channel.UserName);

TLChannel tLChannel = (TLChannel)found.chats.lists[0];
var req = new TLRequestJoinChannel
{
	channel = new TLInputChannel
	{
		channel_id = tLChannel.id,
		access_hash = (long)tLChannel.access_hash
	}
};

TLUpdates resJoinChannel = await client.SendRequestAsync<TLUpdates>(req);


```

**Comment by leila-net** [comment] 2017-07-17 13:30
thanks Mr @hosseinGanjyar 
dear friends, now I have problem whit session.dat file permission after uploading to the server.
the error says :
"Access to the path 'C:\Windows\SysWOW64\inetsrv\session.dat' is denied."

and I used this [link](https://github.com/sochix/TLSharp/issues/351) 's solution for solving the issue,
but now it stopped with null reference exception for httpcontext

**Comment by hadi77ir** [comment] 2017-07-17 14:42
If the problem is solved, close the issue.

**Closed** 2017-07-18 05:37 UTC

**Comment by hosseinGanjyar** [comment] 2017-07-18 12:36
@leila-net please contact to me: @m_h_gj_985618
