### ISSUE TITLE
bann phone number

### ISSUE THREAD

**Issue by PhiseySt** [sochix/TLSharp#504] opened 2017-06-14 13:11 UTC
I tried on 3 phone numbers. The error is PHONE_NUMBER_BANNED. What do I do not so?

My phone number is banned when using the following code:  

...
using TeleSharp.TL;
using TeleSharp.TL.Contacts;
using TLSharp.Core;

...

//  apild=123456 
// apiHash=a646b052c0ffd53e2e650dbd0c213236
//values apild, apiHash get from hyperlink https://my.telegram.org/apps at registration of phone //number

FileSessionStore store = new FileSessionStore();
            var client = new TelegramClient(apild, apiHash
                 , store,
             "session"
            );

            Task<bool> t = client.ConnectAsync();
            bool result = t.Result;

// my phone number with  telegramm client = 79001234567
            Task<string> t1 = client.SendCodeRequestAsync("79001234567");
            string hash = t1.Result;

//   "65695" - code from message in telegramm client, what i get after call procedure SendCodeRequestAsync
            Task<TLUser> t3 = client.MakeAuthAsync("79001234567", hash, "65695");
            TLUser user2 = t3.Result;
// after call procedure MakeAuthAsync,
// the  telegramm client became not available, the message is received in code: //InvalidOperationException: PHONE_NUMBER_BANNED

**Comment by motalebe** [comment] 2017-06-15 22:19
this is vircual number.
telegram banned vircual numbers.

**Comment by PhiseySt** [comment] 2017-06-16 05:43
I have not virtual number (79001234567). The sim card costs in my smartphone. I receive the message with a code (65695) on him

**Comment by Arei15** [comment] 2017-06-17 19:45
Hi gays. Whats happened with Telegram?

**Comment by GetMePower** [comment] 2017-08-31 13:05
Has anyone tracked the cause of the ban?

**Comment by knocte** [comment] 2018-03-12 05:04
Duplicate of https://github.com/sochix/TLSharp/issues/561

**Closed by knocte** 2018-03-12 05:04 UTC
