### ISSUE TITLE
Receiving messages from a bot

### ISSUE THREAD

**Issue by siberianguy** [sochix/TLSharp#731] opened 2018-03-20 10:20 UTC
I'm subscribed to a bot, we have a message history that I'd like to retrieve. I can't figure out how to specify TlAbsInputPeer for a bot. Tried to use a bunch, nothing works. Could you please hint me the right TlAbsInputPeer instance for talking to a bot?

**Comment by knocte** [comment] 2018-03-21 04:00
hey @siberianguy, sorry we don't use Github issues as a forum, but only to report bugs. This is not a bug right? So I'm closing it. Please don't get offended, if you need help using TLSharp, use our gitter or telegram channels (referenced in the README file).

**Closed by knocte** 2018-03-21 04:00 UTC

**Comment by knocte** [comment] 2018-03-21 04:01
(On an unrelated note, is your telegram username @siberianguy too? I wrote you there to ask you a quiestion. Thanks)

**Comment by siberianguy** [comment] 2018-03-21 09:17
@knocte, siberianguy was taken - it's realsiberianguy (stole this idea from realDonaldTrump :) )
