### ISSUE TITLE
WCF

### ISSUE THREAD

**Issue by hosseinGanjyar** [sochix/TLSharp#633] opened 2017-11-16 22:33 UTC
I using this library in my **WCF** project. But when connect to server get below error:
>  : 'AUTH_KEY_UNREGISTERED'

I think this error is for not found **_session.dat_** file in program. 
Where I put session file? Which folder?

 **My code:**
```
public async void HelloWorld()
        {
            var client = new TelegramClient(apiId, apiHash);
            await client.ConnectAsync();

            var dialogs = await client.GetUserDialogsAsync();
        }
```
------------------------------------------------------------------------------------------------------
**Edit 1**:
I want to create new **_session_** file with using '**MakeAuthAsync**' function, but ther is nothing _*.dat_ file in my folder.

**Edit 2**:
I understood, this problem is from search **TLSharp** for _session.dat_ file.

**Comment by knocte** [comment] 2017-11-17 05:35
> But when connect to server get below error:
> 'AUTH_KEY_UNREGISTERED'

This smells to be a duplicate of #624, which has already been fixed.
@hosseinGanjyar have you tested with latest master branch of TLSharp?

**Comment by aarani** [comment] 2017-11-17 17:21
Where's your login part of code ? You just connect and try to fetch user dialogs ?

**Comment by hosseinGanjyar** [comment] 2017-11-18 15:22
I solved problem. 
WCF run from **IIS Express**. I put _session.dat_ file in this folder and run App.

**Closed** 2017-11-18 15:23 UTC
