### ISSUE TITLE
await client.SendCodeRequestAsync Null reference expection

### ISSUE THREAD

**Issue by TERMI80** [sochix/TLSharp#608] opened 2017-10-18 22:08 UTC
Dear Sirs,
i try to use this fantastic library but i have some problem:
my code is:
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TLSharp;
using TeleSharp.TL;
using TLSharp.Core;
namespace TLC
{
    class Program
    {

        static string phoneCodeHash;
        static void Main(string[] args)
        {

            Run();

        }
      static  async void Run()
        {
            var store = new FileSessionStore();
            string Alert = "ciao";
           TLUser user = null;
            var client = new TelegramClient(114, "b429bd4470c9b2ba4a", store);

            if (client.IsUserAuthorized())
            {
                //get available contacts
                var result = await client.GetContactsAsync();

                //find recipient in contacts
             //   var userr = result.users.lists.Where(x => x.GetType() == typeof(TLUser)).Cast<TLUser>().FirstOrDefault(x => x.phone == "98" + TextBox1.Text);

                //send message
                await client.SendMessageAsync(new TLInputPeerUser() { user_id = user.id }, Alert);
            }
            else
            {
                phoneCodeHash = await client.SendCodeRequestAsync("3933928");
            }

        }
    }
}

The excption is:

in TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__13.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   in TLC.Program.<Run>d__2.MoveNext() in C:\Users\Davide\source\repos\TLC\TLC\Program.cs:riga 43

**Comment by knocte** [comment] 2017-10-19 03:08
NullReferenceExceptions are easy to debug and fix. If you find that this is happening inside TLSharp, please contribute a PullRequest to fix it. Thanks!

**Comment by TERMI80** [comment] 2017-10-19 06:14
Hello,
Could you help me to fix it?
It's also possible create automatic cose for authentication without ask a code?
Do you have some project to download for test but not only class project.
Thanks Davide

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by knocte** [comment] 2017-10-19 06:18
Sorry, I cannot really help because I can't reproduce your exception in my system.
Once you bring up the fix as a pull request, I will review your code and merge it into master branch.

**Comment by TERMI80** [comment] 2017-10-19 06:32
Hello,
In which way i can pull request?
If you want i can send my project, did you see my code there si something wrong?
Davide

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by knocte** [comment] 2017-10-19 06:33
There are many tutorials on the internet that teach you about how to make a pull request in Github, please google about it.

**Comment by TERMI80** [comment] 2017-10-19 10:04
Sorry but i try to make a pull request but i have some problem there is another way to check my code.. i also add fakesessionstore(); but i got alway execption.
Davide

**Comment by hjalalisharepoint2013** [comment] 2017-11-15 05:43
Hi, I have the same problem and this problem **not exist in 0.1.0.270** version!
I tested it multiple times and also with different dependent assemblies.
Please consider fixing it since literally we can't do nothing.

**Comment by knocte** [comment] 2017-11-15 06:54
@hjalalisharepoint2013 we would fix it if we knew how to reproduce it! If you can reproduce it, please fix it and provide a PullRequest. Thanks

**Comment by hjalalisharepoint2013** [comment] 2017-11-15 07:39
@knocte OK, i'll try.

**Comment by hjalalisharepoint2013** [comment] 2017-11-15 08:43
@knocte I debugged it and when _sender.Receive(in RequestWithDcMigration method) execute then an exception of type "DataCenterMigrationException" occurs with this message:
`Phone number registered to a different DC: 4. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error`
After that ReconnectToDcAsync method and ConnectAsync ran and when "await RequestWithDcMigration(request);" is done then "return request.Response.PhoneCodeHash;
" is ran which request.**Response** is null and when PhoneCodeHash is called then the null error occurs.

**Comment by knocte** [comment] 2017-11-15 08:47
@hjalalisharepoint2013 good analysis! Can you contribute a bugfix please?

@Grepsy maybe your last commit introduced this problem? See above the use of RequestWithDcMigration() method that you created.

**Comment by hjalalisharepoint2013** [comment] 2017-11-15 09:00
@knocte 

> Can you contribute a bugfix please?

What should i do exactly?

**Comment by knocte** [comment] 2017-11-15 09:03
@hjalalisharepoint2013 you have never contributed a pull request to a github project? there are many tutorials out there

**Comment by Grepsy** [comment] 2017-11-15 09:06
I can dig into it later, but can someone give me a full stacktrace. I can't make sense of the one provided in opening post.

**Comment by knocte** [comment] 2017-11-15 09:07
@hjalalisharepoint2013 please provide a full stacktrace to Grepsy

**Comment by hjalalisharepoint2013** [comment] 2017-11-15 09:19
@knocte, @Grepsy here is full stack, hope it helps.
When exception of type "DataCenterMigrationException" occurs:
![image](https://user-images.githubusercontent.com/33659915/32827825-a66b2e64-ca02-11e7-9f8c-0917b8784983.png)
`   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in C:\Softwares\Codes\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 294
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in C:\Softwares\Codes\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 206
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext() in C:\Softwares\Codes\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__11.MoveNext() in C:\Softwares\Codes\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 106`

And in the end when the Response is null:
![image](https://user-images.githubusercontent.com/33659915/32828014-380a82d4-ca03-11e7-9d6b-73082f7a397a.png)

**Comment by Grepsy** [comment] 2017-11-15 09:29
Thank you, that's helpful! I'll check later today.

**Comment by hjalalisharepoint2013** [comment] 2017-11-15 12:04
@TERMI80 before calling this line of code:
`phoneCodeHash = await client.SendCodeRequestAsync("3933928");`
You should call `client.ConnectAsync()` method first.

**Comment by Grepsy** [comment] 2017-11-15 19:08
I'm trying to reproduce this but can't seem to trigger the error. Can one or you post a minimal example that crashes? Also please try running the `AuthUser` unit-test and see if that fails for you as well (it doesn't for me).

**Comment by knocte** [comment] 2017-11-16 12:20
maybe it doesn't happen anymore with latest master? @hjalalisharepoint2013 can you try again with the last commits merged today?

**Comment by AskoldMakaruk** [comment] 2017-11-19 10:36
@hjalalisharepoint2013 try to use something like this before SendCodeRequestAsync `while(!client.IsConnected)
                    {
                        Thread.Sleep(600);
                    }`
Since its async codeRequest can be called before client connects to server, so you need to wait until its over.

**Comment by hjalalisharepoint2013** [comment] 2017-11-20 07:03
@Grepsy I can send you an example but don't think the error is in my codes instead i think it has something to do with the phone number which recognized as "different DC" or something like that!:
![image](https://user-images.githubusercontent.com/33659915/33005811-d07d6680-cddc-11e7-87e9-3f039b4d9a96.png)
Unfortunately i can't provide you a test phone number with api key and all. Since in 0.1.0.270 version everything was OK and if you could provide the source download link for that version i think i can compare and find the problem and fix it.

@knocte i think i tested the latest version, but can i ask what changes is made which makes you think it fixed the problem?

@AskoldMakaruk thanks for it, @Grepsy what you think about `Thread.Sleep`?

**Comment by hjalalisharepoint2013** [comment] 2017-11-20 12:32
I tested more and found out that this problem only happens when the client application is an asp.net(mvc) application.
In console and windows application and Visual Studio test environment its OK!
But when using in an asp.net mvc application, it returns an error:
System.NullReferenceException: Object reference not set to an instance of an object. 
```
Line 145:            return request.Response.PhoneCodeHash;
Line 146:        }
```
`Source File: C:\Softwares\Codes\TLSharp-master\TLSharp.Core\TelegramClient.cs    Line: 145`

So @Grepsy the `AuthUser` unit test was OK.
Also mention that this error doesn't happen in 0.1.0.270 version even when used in an asp.net application!

**Comment by Grepsy** [comment] 2017-11-20 20:19
Thanks for the code @hjalalisharepoint2013. Took me some time but I think I finally figured out the problem. The problem only occurs when a reconnect is required during the `GetAuthCode` call, and only when there is no session saved yet. On a second run it will connect to the right DC so no migration is triggered.

What happens is the `request` gets re-used and a property called `ConfirmReceived` is still true from the first request (the one that triggered the migration). This means that `Receive` is called using the same `request` it won't actually receive anything.
```
public async Task<byte[]> Receive(TeleSharp.TL.TLMethod request)
        {
            while (!request.ConfirmReceived)
```

This bug was partially introduced by my PR. In the previous code there were other call sites where the request was also re-used, which is what I used for my implementation. The `GetAuthCode` call did not re-use the request and was hence free of this bug.

I believe the simplest solution will be to simple set `ConfirmReceived` to `false` when re-sending a `request`.

**Comment by hjalalisharepoint2013** [comment] 2017-11-21 06:56
@Grepsy Thanks man. It also fixed the "PHONE_CODE_EXPIRED" problem which happens when instantiating `TelegramClient` again to run `MakeAuthSession` method with the login code received from telegram.
It means now we can use this in our web applications to authenticate and create the session file.

**Closed** 2017-11-21 13:02 UTC

**Comment by knocte** [comment] 2017-11-21 13:08
Awesome work @Grepsy !

BTW, the flood exception seems to be a constant complain from TLSharp users. I wonder if there's a bug in the library that causes the TLSharp-client to spam the servers. If you still have that sniffer set up you could compare the traffic of your TLSharp app with other traffic from an official Telegram client (e.g. the Telegram desktop app) and try to catch on what we differ? Anyway this is a discussion for other github issue (I believe there already some of them open about this).

**Comment by freezepro** [comment] 2017-12-04 23:13
Hi. So I dont have NullReference exception on following

var phonehash = client.SendCodeRequestAsync( phone);

 hash = phonehash.Result; 

but when it tries to get result, app just hangs(in debug mode even) ,so nothing goes further

**Comment by knocte** [comment] 2017-12-05 06:18
@freezepro: 2 things:

- Are you using latest git master?
- Please, if it's not a NullReferenceException, this doesn't belong to this github issue, open a new github issue instead.

**Comment by freezepro** [comment] 2017-12-13 23:07
@knocte it is but rarely, It happened once or two times. I looked at phonehash object before calling .Result, it contains exception(says that connection couldn't be created/socket one). I tried to turn some apps, looks like dissapeared but original issue(when app just hangs still present). 
Creating new issue.
