### ISSUE TITLE
TLSharp.Core.Network.PhoneMigrationException

### ISSUE THREAD

**Issue by ivanovaleksey** [sochix/TLSharp#290] opened 2016-11-04 20:22 UTC
Hi!
Thank for the nice library.

I would like to use in order to check if phone is registered in Telegram.
But I've faced with an issue.

Here is my simple code
```
int apiId = APP_ID;
string apiHash = APP_HASH;

var client = new TelegramClient(apiId, apiHash);
await client.ConnectAsync();
var result = await client.IsPhoneRegisteredAsync(PHONE_NUMBER);
```

Unfortunately I am getting an error
```
An exception of type 'TLSharp.Core.Network.PhoneMigrationException' occurred in mscorlib.dll but was not handled in user code

Additional information: Phone number registered to a different DC: 2. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error
```

Is said that the library should automatically handle these errors. But it doesn't happen.

In my application settings I have the following DC configuration.
![image](https://cloud.githubusercontent.com/assets/11523473/20021307/4e71b19a-a2e6-11e6-9aab-171a4b48811f.png)
 
Can I specify DC to be used? 
I have tried to google the error but I didn't find any solution.
What can I do? Am I doing something wrong?

Thanks in advance.

**Comment by ivanovaleksey** [comment] 2016-11-04 22:08
I have noticed that `SendCodeRequestAsync()` catches `PhoneMigrationException` exception and reconnects to proper DC. So I just added `SendCodeRequestAsync()` call and now it works fine.

But `IsPhoneRegisteredAsync()` should work without authorization. Is it correct that I should call `SendCodeRequestAsync()` anyway?

**Comment by knocte** [comment] 2016-11-05 04:34
> Is it correct that I should call SendCodeRequestAsync() anyway?

Don't think it's correct, sounds like a workaround. We're probably missing the same `catch(PhoneMigrationException){ ... Reconnect(...) }` in `IsPhoneRegisteredAsync()`, do you mind creating a pull request to fix it?

**Comment by ivanovaleksey** [comment] 2016-11-05 06:33
To be honest I am Ruby developer and I have very basic knowledges of C#. 
But I would like to contribute to the project so I will do my best!

**Comment by aarani** [comment] 2016-11-05 16:27
@ivanovaleksey @knocte There's no need you can return true on PhoneMigrationException because it show that user exist on telegram 👍

**Comment by ivanovaleksey** [comment] 2016-11-05 16:52
@aarani That sounds interesting. I should try it!

**Comment by ivanovaleksey** [comment] 2016-11-05 17:17
`PhoneMigrationException` [seems to be ](https://github.com/sochix/TLSharp/blob/master/TLSharp.Core/Network/MtProtoSender.cs#L526-L532) internal class.
Does it mean that I can't use it in `catch` like?
```
try {
   ...
} catch (PhoneMigrationException) {
   ...
}
```

**Comment by knocte** [comment] 2016-11-05 17:19
It means you cannot catch it outside TLSharp.Core. However, to fix this bug, you should catch it inside.

**Comment by sochix** [comment] 2016-11-08 12:45
Bug confirmed. Will fix it.

**Comment by 4ndv** [comment] 2016-11-16 07:43
Also got this error while trying to send CheckPhone via SendRequestAsync:

```csharp
var req = new TLRequestCheckPhone()
{
     phone_number = "79999991234"
};
var available = await client.SendRequestAsync<Boolean>(req);
```

**Comment by knocte** [comment] 2016-11-28 09:26
This has been fixed in https://github.com/sochix/TLSharp/commit/545e73680868464a969f000ea683d7e85be685b9 . @sochix  can you close?

**Closed** 2016-11-28 09:38 UTC
