### ISSUE TITLE
app crash at create "new TelegramClient" object

### ISSUE THREAD

**Issue by ram-sh** [sochix/TLSharp#859] opened 2019-07-03 15:40 UTC
Hello,

using TLSharp 0.1.0.390

app crash at create new TelegramClient object :(

`Unhandled Exception: System.Net.Sockets.SocketException: The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpClient..ctor(IPEndPoint localEP)
   at TLSharp.Core.Network.TcpTransport..ctor(String address, Int32 port, TcpClientConnectionHandler handler)
   at TLSharp.Core.TelegramClient..ctor(Int32 apiId, String apiHash, ISessionStore store, String sessionUserId, TcpClientConnectionHandler handler)`

what is it i'm missing here?

thank you in advance!!

**Comment by eordukaya** [comment] 2019-07-03 16:04
I get the same exception. I was using working code. but todey I get this exception.

**Comment by CloneDeath** [comment] 2019-07-03 17:21
Are you able to get what IP Address it's trying to use?
What does Socket.OSSupportsIPv6 return?
What OS are you running on?

I suspect it's IPv6, and your computer doesn't support it. Answering the above question may shed some light on that theory.

**Comment by eordukaya** [comment] 2019-07-03 20:54
public TcpTransport(string address, int port, TcpClientConnectionHandler handler = null)
 {
   if (handler == null)
   {
       var ipAddress = IPAddress.Parse(address);
       var endpoint = new IPEndPoint(ipAddress, port);

       _tcpClient = new TcpClient(endpoint);
       _tcpClient.Connect(endpoint);
   }
   else
   _tcpClient = handler(address, port);
 }

I get an ip adress like 149.134.145.100:443
I m using win10.

the exception is in TcpTransport.cs file and in this line
_tcpClient = new TcpClient(endpoint);

![Ekran Alıntısı](https://user-images.githubusercontent.com/34960896/60624278-8c68d000-9ded-11e9-852c-3e697911a7a4.PNG)

**Comment by ram-sh** [comment] 2019-07-05 05:51
is it just us? everyone else doesn't have this error?

**Comment by knocte** [comment] 2019-07-05 08:08
@eordukaya can you be more specific? do you get `149.134.145.100:443` in the `address` variable? including the colon and the port?

**Comment by eordukaya** [comment] 2019-07-05 08:42
after this statement I get exception 
var endpoint = new IPEndPoint(ipAddress, port);
I looked endpoint and variable is 149.134.145.100:443

**Comment by knocte** [comment] 2019-07-05 08:46
@eordukaya I didn't ask you to look at `ipAddress` variable but to `address` variable.

Anyway, seems correct. Can you revert commit `3224113e4ce827319c049f44ee5a759ad1591fa0` and tell us if it connects successfully to the same IP address?

**Comment by eordukaya** [comment] 2019-07-05 09:18
I update this commit but get exception again in this line.
![Ekran Alıntısı](https://user-images.githubusercontent.com/34960896/60712139-08166a00-9f1f-11e9-8ac9-5cf5f5e47559.PNG)

**Comment by knocte** [comment] 2019-07-05 09:19
That's not a proper revert, you're creating a TcpClient instance twice. Do `git revert 3224113e4ce827319c049f44ee5a759ad1591fa0` instead of doing it manually.

**Comment by eordukaya** [comment] 2019-07-05 09:32
Ok I understand. I download fixed TLSharp with 3224113e4ce827319c049f44ee5a759ad1591fa0 . But I get exception again. I added my debug photos.

![1](https://user-images.githubusercontent.com/34960896/60712917-afe06780-9f20-11e9-8a61-26449501e82c.png)

![2](https://user-images.githubusercontent.com/34960896/60712921-b242c180-9f20-11e9-8883-2ca9b0d75455.png)

![3](https://user-images.githubusercontent.com/34960896/60712924-b40c8500-9f20-11e9-9011-6cf0dabe2557.png)

![4](https://user-images.githubusercontent.com/34960896/60712928-b5d64880-9f20-11e9-8420-288cc198533f.png)

![1111](https://user-images.githubusercontent.com/34960896/60712938-bcfd5680-9f20-11e9-8c90-fc12f51b600f.png)

![2222](https://user-images.githubusercontent.com/34960896/60712939-be2e8380-9f20-11e9-9822-34ed2b3ef2f8.png)

![3333](https://user-images.githubusercontent.com/34960896/60712942-bf5fb080-9f20-11e9-895a-9cf0e3f3f8c5.png)

![44444](https://user-images.githubusercontent.com/34960896/60712946-c1297400-9f20-11e9-8ef9-2bad76846922.PNG)

**Comment by knocte** [comment] 2019-07-05 09:36
Man, you're not reverting the commit I'm telling you. If you see a variable `endpoint` in the code, then it means you're not testing what I'm telling you. You're just testing latest master.

**Comment by byguid** [comment] 2019-07-05 10:01
@knocte , had the same problem, reverting your suggested commit `3224113e4ce827319c049f44ee5a759ad1591fa0` fixed the issue.

**Comment by knocte** [comment] 2019-07-05 10:45
@byguid and what's the IP address that you connected and tried to connect (when not reverting)? Same?

**Comment by byguid** [comment] 2019-07-05 10:55
@knocte, yes, the address was the same in both cases.

**Comment by eordukaya** [comment] 2019-07-05 15:08
@ram-sh  @knocte I reverted code block in edited file (for IPv6) TcpTransport.cs
I deleted this block;

if (handler == null)
{
   var ipAddress = IPAddress.Parse(address);
   var endpoint = new IPEndPoint(ipAddress, port);
   _tcpClient = new TcpClient(endpoint);
   _tcpClient.Connect(endpoint);
}
else
   _tcpClient = handler(address, port);

I added this block instead of before

if (handler == null)
{
   _tcpClient = new TcpClient();
   var ipAddress = IPAddress.Parse(address);
   _tcpClient.Connect(ipAddress, port);
}
else
   _tcpClient = handler(address, port);

Then it works.

**Comment by knocte** [comment] 2019-07-05 15:10
@CloneDeath so apparently your commit broke this, did you test it?

**Comment by eordukaya** [comment] 2019-07-05 15:25
@CloneDeath @knocte if commit works on ipV6, can be done;
if ipv6 use new
else use old
then you can new commit.

**Comment by knocte** [comment] 2019-07-05 15:27
But @CloneDeath's patch was supposed to work with both, we checked in the MSDN documentation.

**Comment by eordukaya** [comment] 2019-07-05 15:31
ok, I reported that old version works but new doesnt. @CloneDeath can check again. thanks for everything.

**Comment by ram-sh** [comment] 2019-07-06 07:37
@eordukaya solution worked for me as well! thanks much!!

**Closed** 2019-07-06 10:52 UTC

**Comment by knocte** [comment] 2019-07-11 23:37
This issue is duplicate of https://github.com/sochix/TLSharp/issues/862 , which has just been fixed.
