### ISSUE TITLE
SendCodeRequestAsync causing NullReferenceException

### ISSUE THREAD

**Issue by idb-** [sochix/TLSharp#637] opened 2017-11-21 16:12 UTC
Am getting a nullref ex when trying to request hash. Apparently this is being caused due to a PhoneMigrationException. Am seeing this in the intellitrace window:

> Exception:Caught: "Phone number registered to a different DC: 1. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error" (TLSharp.Core.Network.PhoneMigrationException)
> A TLSharp.Core.Network.PhoneMigrationException was caught: "Phone number registered to a different DC: 1. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error"
> Time: 11/21/2017 11:03:37 AM
> Thread:<No Name>[92832]

which is in turn causing this:

> A first chance exception of type 'System.NullReferenceException' occurred in mscorlib.dll
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Telegram_Example.Form1.VB$StateMachine_0_Button1_Click.MoveNext() in <Redacted>\Form1.vb:line 32

I'm also having an issue with loading the session.dat information from file and reconnecting. Is saying that the hash doesn't exist or something. Will get a more descriptive error when I see it again. 

Any ideas?

**Comment by hjalalisharepoint2013** [comment] 2017-11-25 11:17
Please refer to this issue, might help:
https://github.com/sochix/TLSharp/issues/608

**Comment by knocte** [comment] 2017-11-25 11:36
@idb- are you using latest master branch?

**Comment by idb-** [comment] 2017-11-26 03:42
@knocte i installed through nuget

**Comment by knocte** [comment] 2017-11-26 03:46
@idb- not sure if nuget has the last version because I'm not in charge of uploading it. Can you try cloning master branch instead?

**Comment by knocte** [comment] 2018-03-01 07:45
@idb- we didn't get any news from you so I'm closing this. If you `git pull` from our repository instead of using nuget, and can still reproduce this issue, please reopen this.

**Closed by knocte** 2018-03-01 07:45 UTC
