### ISSUE TITLE
Sending message works when I run the project in visual studio IDE, but doesn't work when publish on IIS

### ISSUE THREAD

**Issue by mersi77** [sochix/TLSharp#326] opened 2016-11-30 09:11 UTC
Is there anybody to help?

**Comment by knocte** [comment] 2016-11-30 09:42
Is this issue a duplicate of https://github.com/sochix/TLSharp/issues/314 ?

**Comment by sochix** [comment] 2016-11-30 09:51
@mersi77 I bet problem in storage on IIS. It just can't save session.dat

**Comment by mersi77** [comment] 2016-11-30 14:57
What can I do to solve this problem?

**Comment by mersi77** [comment] 2016-12-16 05:25
Is it possible to change the location of session.dat?

**Closed** 2016-12-16 08:08 UTC
